
import java.util.ArrayList;
import java.util.List;

/**
 * This class represents a course with its CRN, course name, instructor, and a
 * list of assignments.
 * 
 * DO NOT EDIT THIS FILE.
 *
 * @author Prof. White
 * @version Spring 2026
 */
public class Course {

    /**
     * The CRN (unique identifier) of the course.
     */
    private String crn;

    /**
     * The name of the course.
     */
    private String courseName;

    /**
     * The instructor of the course.
     */
    private String instructor;

    /**
     * The list of students enrolled in the course.
     */
    private List<Student> students;

    /**
     * Constructs a Course object with the specified CRN, course name, and
     * instructor.
     *
     * @param crn the course registration number
     * @param courseName the name of the course
     */
    public Course(String crn, String courseName) {
        this.crn = crn;
        this.courseName = courseName;
        students = new ArrayList<>();
    }

    /**
     * Constructs a Course object with the specified CRN, course name, and
     * instructor.
     *
     * @param crn the course registration number
     * @param courseName the name of the course
     * @param instructor the name of the instructor
     */
    public Course(String crn, String courseName, String instructor) {
        this.crn = crn;
        this.courseName = courseName;
        this.instructor = instructor;
        students = new ArrayList<>();
    }

    /**
     * Returns the CRN of the course.
     *
     * @return the CRN of the course
     */
    public String getCrn() {
        return crn;
    }

    /**
     * Returns the name of the course.
     *
     * @return the name of the course
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Returns the name of the instructor for the course.
     *
     * @return the name of the instructor for the course
     */
    public String getInstructor() {
        return instructor;
    }

    /**
     * Updates the instructor for the course.
     *
     * @param instructor the name of the new instructor for the course
     */
    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }

    /**
     * Adds a student to the course.
     *
     * @param student the student to be added
     */
    public void addStudent(Student student) {
        if (!students.contains(student)) {
            students.add(student);
        }
    }

    /**
     * Returns a string representation of the course.
     *
     * @return a string representation of the course
     */
    @Override
    public String toString() {
        StringBuilder studentsStr = new StringBuilder();
        for (Student student : students) {
            studentsStr.append(student.toString()).append("\n");
            //studentsStr.append("***********************************************\n");
        }

        return "Course{"
                + "crn=" + crn 
                + ", courseName=" + courseName
                + ", instructor=" + instructor
                + "\nstudents=" + studentsStr
                + '}';
    }
}
