/**
 * This class represents a number of points earned and the total possible points.
 * 
 * DO NOT EDIT THIS FILE.
 * 
 * @author Prof. White
 * @version Spring 2026
 */
public class GradePair {
    private int pointsEarned;
    private int totalPoints;

    /**
     * Constructs a GradePair object with the specified points earned and total points.
     *
     * @param pointsEarned the number of points earned
     * @param totalPoints the total possible points
     */
    public GradePair(int pointsEarned, int totalPoints) {
        this.pointsEarned = pointsEarned;
        this.totalPoints = totalPoints;
    }

    /**
     * Returns the number of points earned.
     *
     * @return the number of points earned
     */
    public int getPointsEarned() {
        return pointsEarned;
    }

    /**
     * Returns the total possible points.
     *
     * @return the total possible points
     */
    public int getTotalPoints() {
        return totalPoints;
    }

    /** 
     * Returns a string representation of the GradePair. 
     * 
     * @return a string representation of the GradePair
     */
    @Override
    public String toString() {
        return pointsEarned + "/" + totalPoints;
    }
}