
import java.util.ArrayList;
import java.util.List;

/**
 * Student class represents a student with an ID, name, and a list of courses
 * they are enrolled in.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @author Prof. White
 * @version Spring 2026
 */
public class Student {

    /**
     * The unique ID of the student.
     */
    private String id;

    /**
     * The name of the student.
     */
    private String name;

    /**
     * The list of assignments for the student.
     */
    private List<Assignment> assignments;

    /**
     * Constructs a Student object with the specified ID and name.
     *
     * @param id the student's ID
     * @param name the student's name
     */
    public Student(String id, String name) {
        this.id = id;
        this.name = name;
        this.assignments = new ArrayList<>();
    }

    /**
     * Returns the ID of the student.
     *
     * @return the ID of the student
     */
    public String getId() {
        return id;
    }

    /**
     * Returns the name of the student.
     *
     * @return the name of the student
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the list of assignments the student has.
     *
     * @return the list of assignments the student has
     */
    public List<Assignment> getAssignments() {
        return assignments;
    }

    /**
     * Adds an assignment to the student's list of assignments.
     *
     * @param assignment the assignment to be added
     */
    public void addAssignment(Assignment assignment) {
        assignments.add(assignment);
    }

    /**
     * Checks if this student is equal to another object based on their ID.
     *
     * @param obj the object to compare with
     * @return true if the other object is a Student with the same ID, false
     * otherwise
     */
    @Override
    public boolean equals(Object obj) {
        if (obj != null && obj instanceof Student) {
            Student other = (Student) obj;
            return this.id.equals(other.id);
        }
        return false;
    }

    /**
     * Returns the hash code for this student based on their ID.
     *
     * @return the hash code for this student
     */
    @Override
    public int hashCode() {
        return id.hashCode();
    }

    /**
     * Returns a string representation of the Student object.
     *
     * @return a string representation of the Student object
     */
    @Override
    public String toString() {
        StringBuilder assignmentsStr = new StringBuilder();
        for (Assignment assignment : assignments) {
            assignmentsStr.append(assignment.toString()).append("\n");
        }
        return "Student ID: " + id + ", Name: " + name + "\nAssignments:\n" + assignmentsStr.toString();
    }
}
